# -*- coding: utf-8 -*-
"""How_secure_is_cyberspace_final_file_for analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkWhzerEMSZVbN1enME9ml3yFchPP1Le
"""

from google.colab import files, drive
from pathlib import Path
import pandas as pd

# drive.mount('/content/drive')

# look for csv files in the directory
directory = '/content/drive/MyDrive/11_Kyberkriminalita/data/'

path = Path(directory)
all_files = [file.stem for file in path.glob('*.csv')]

print(f"There are {len(all_files)} files to process.")

# define dict with column names
names_dict = {
  'utvar' : 'utvar',
  'rok' : 'rok', 
  'Unnamed: 0' : 'TSK',
  '|registrované skutky' : 'ck_skutky',
  'z toho objasněno' : 'ck_objasněno', 
  'z toho spách. ženami' : 'ck_spácháno_ženy', 
  'z toho spách. muži' : 'ck_spácháno_muži', 
  'z toho spách. cizinci' : 'ck_spácháno_cizinci', 
  'z toho spách. dětmi do 18ti let' : 'ck_spácháno_děti_do18let', 
  'z toho spách. nezl. do 15ti let' : 'ck_spácháno_děti_do15let', 
  'z toho spách. mladist 15-17let' : 'ck_spácháno_mladiství', 
  'z toho spách. dospělými od 18ti let vč.' : 'ck_spácháno_dospělí', 
  'objasněno dodatečně' : 'ck_objasněno_dodatečně', 
  'objasněno celkem' : 'ck_objasněno_celkem', 
  '|registrované skutky.1' : 'kk_skutky', 
  'z toho objasněno.1' : 'kk_objasněno', 
  ' z toho spách. ženami' : 'kk_spácháno_ženy', 
  'z toho spách. muži.1' : 'kk_spácháno_muži', 
  'z toho spách. cizinci.1' : 'kk_spácháno_cizinci', 
  'z toho spách. dětmi do 18ti let.1' : 'kk_spácháno_děti_do18let', 
  'z toho spách. nezl. do 15ti let.1' : 'kk_spácháno_děti_do15let', 
  'z toho spách. mladist 15-17let.1' : 'kk_spácháno_mladiství', 
  'z toho spách. dospělými od 18ti let vč..1' : 'kk_spácháno_dospělí', 
  'objasněno dodatečně.1' : 'kk_objasněno_dodatečně', 
  'objasněno celkem.1' : 'kk_objasněno_celkem', 
  '|osoby celkem' : 'ck_osoby_celkem', 
  'ženy' : 'ck_ženy', 
  'muži' : 'ck_muži', 
  'cizinci' : 'ck_cizinci', 
  'věk do 18ti let' : 'ck_do18let', 
  'věk do 15ti let' : 'ck_do15let',
  'věk 15-17 let' : 'ck_mladiství',
  ' dospělí 18 a více let' : 'ck_dospělí',
  '|osoby celkem.1' : 'kk_osoby_celkem', 
  'ženy.1' : 'kk_ženy', 
  'muži.1' : 'kk_muži', 
  'cizinci.1' : 'kk_cizinci', 
  'věk do 18ti let.1' : 'kk_do18let', 
  'věk do 15ti let.1' : 'kk_do15let',
  'věk 15-17 let.1' : 'kk_mladiství',
  'dospělí 18 a více let' : 'kk_dospělí',
  '|celk.škoda' : 'ck_škoda',
  'z toho kyber' : 'kk_škoda'
}

# create dataframe
df_main = pd.DataFrame(columns = list(names_dict.keys()))
display(df_main)

for i, file in enumerate(all_files):
  print(f"Processing file {i}/{len(all_files)}")
  df = pd.read_csv(
    filepath_or_buffer=directory+file+'.csv', 
    encoding='cp1250',
    delimiter=';',
    skiprows=[0, 1]
  )
  
# get unit and year from the file name
  file_name = file.split('_')
  unit = file_name[0]
  year = file_name[1]
  df.insert(0, 'utvar', unit)
  df.insert(1, 'rok', year)
  df_main = df_main.append(df, ignore_index=True)

df_main.rename(columns=names_dict, inplace=True)

# select only the rows with at least one registred act
df_main = df_main[df_main['ck_skutky'] > 0] 

df_main.to_csv('final_file.csv', encoding='cp1250')
files.download('final_file.csv')